# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0002_auto_20160705_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('1', 'Division 1'), ('2', 'Division 2')], max_length=1)),
            ],
        ),
    ]
