# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minos', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='login',
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
