# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0004_auto_20160710_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('correct', models.BooleanField()),
                ('submission_time', models.DateField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minos.Question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minos.Team')),
            ],
        ),
    ]
