# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0006_auto_20160713_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minos.Question'),
        ),
    ]
