# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0007_auto_20160713_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_in', models.TextField()),
                ('standard_out', models.TextField()),
                ('error_viewable', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minos.Question')),
            ],
        ),
    ]
