# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0008_testcases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
