# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0009_auto_20160713_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
