# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0013_startercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startercode',
            name='language',
            field=models.CharField(choices=[('ace/mode/java', 'Java (7)'), ('ace/mode/python', 'Python (2)'), ('ace/mode/python-3', 'Python (3)'), ('ace/mode/vbscript', 'Visual Basic'), ('ace/mode/c_cpp', 'C++'), ('ace/mode/csharp', 'C#')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('ace/mode/java', 'Java (7)'), ('ace/mode/python', 'Python (2)'), ('ace/mode/python-3', 'Python (3)'), ('ace/mode/vbscript', 'Visual Basic'), ('ace/mode/c_cpp', 'C++'), ('ace/mode/csharp', 'C#')], max_length=20),
        ),
    ]
