# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0014_auto_20160726_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='startercode',
            name='language',
            field=models.CharField(choices=[('ace/mode/java', 'Java 7'), ('ace/mode/python', 'Python 2'), ('ace/mode/python-3', 'Python 3'), ('ace/mode/vbscript', 'Visual Basic'), ('ace/mode/c_cpp', 'C++ 11'), ('ace/mode/csharp', 'C#')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('ace/mode/java', 'Java 7'), ('ace/mode/python', 'Python 2'), ('ace/mode/python-3', 'Python 3'), ('ace/mode/vbscript', 'Visual Basic'), ('ace/mode/c_cpp', 'C++ 11'), ('ace/mode/csharp', 'C#')], max_length=20),
        ),
    ]
