# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0015_auto_20160729_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minos.Contest'),
            preserve_default=False,
        ),
    ]
