# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0016_question_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minos.Contest'),
        ),
    ]
